# @format

version: "3"

services:
    referencias_db:
        image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
        restart: always
        ports:
            - "1434:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=oSpEcONSQL3578951
            - MSSQL_PID=Express
        volumes:
            - ./referencias_data-mssql:/var/opt/mssql/data
    portainer:
        image: portainer/portainer-ce
        ports:
            - "8000:8000"
            - "9000:9000"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer_data:/data

    referencias_api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - referencias_db
        ports:
            - "5000:80"
            - "5001:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80

networks:
    default:
